// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkapHSWiNjWuNiLAwhM8kqyxEoGnCnaYg',
    appId: '1:952348910877:ios:b3591528802f6f32922df4',
    messagingSenderId: '952348910877',
    projectId: 'medplant-1',
    storageBucket: 'medplant-1.firebasestorage.app',
    iosBundleId: 'com.example.medplant',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5XPbz1tdHOzMbQLwrU8jmMu9AxhqvuiA',
    appId: '1:952348910877:web:d24f32d4df625db7922df4',
    messagingSenderId: '952348910877',
    projectId: 'medplant-1',
    authDomain: 'medplant-1.firebaseapp.com',
    storageBucket: 'medplant-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkapHSWiNjWuNiLAwhM8kqyxEoGnCnaYg',
    appId: '1:952348910877:ios:b3591528802f6f32922df4',
    messagingSenderId: '952348910877',
    projectId: 'medplant-1',
    storageBucket: 'medplant-1.firebasestorage.app',
    iosBundleId: 'com.example.medplant',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy5Ucbnzd4G84FWAE0KDFlHWn64ZqqgxY',
    appId: '1:952348910877:android:982d7b2ab471f466922df4',
    messagingSenderId: '952348910877',
    projectId: 'medplant-1',
    storageBucket: 'medplant-1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5XPbz1tdHOzMbQLwrU8jmMu9AxhqvuiA',
    appId: '1:952348910877:web:26e1b49192984075922df4',
    messagingSenderId: '952348910877',
    projectId: 'medplant-1',
    authDomain: 'medplant-1.firebaseapp.com',
    storageBucket: 'medplant-1.firebasestorage.app',
  );

}